version: '3.2'
services:
  jupyter-lab:
    image: "docker.io/goldentigerindia/jupyter-hub:latest"
    environment:
      - USER_NAME=admin
    ports:
      - "9999:9999"
    volumes:
      - type: bind
        source: ./jupyter
        target: /home/admin/jupyter
